#!/bin/sh

remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid
do
  yarn lint
  if [ $? -ne 0 ]; then
    echo "Lint error"
    exit 1
  else
    echo "Lint ok"
  fi

  yarn compile
  if [ $? -ne 0 ]; then
    echo "Compile error"
    exit 1
  else
    echo "Compile ok"
  fi
done

exit 0
